# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2016-04-20 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20160419_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='junior',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='junior',
            name='view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='middle',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='middle',
            name='view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='junior',
            name='deep_learn_subject',
            field=models.ManyToManyField(related_name='jun_deep_learn_subjects', to='tests.DeepLearnSubjects'),
        ),
        migrations.AlterField(
            model_name='middle',
            name='deep_learn_subject',
            field=models.ManyToManyField(related_name='mid_deep_learn_subjects', to='tests.DeepLearnSubjects'),
        ),
    ]
