# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20160420_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepareToEnter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Способ')),
            ],
            options={
                'verbose_name_plural': 'Способы подготовки к поступлению',
                'verbose_name': 'Способ подготовки к поступлению',
            },
        ),
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('view', models.BooleanField(default=False)),
                ('school_class', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('future_prof', models.CharField(max_length=200)),
                ('after_school', models.CharField(max_length=200)),
                ('have_chosen_inst', models.CharField(max_length=200)),
                ('have_chosen_training', models.CharField(max_length=200)),
                ('if_you_want_ugtu', models.CharField(max_length=200)),
                ('if_you_want_ugtu_training', models.CharField(max_length=200, null=True)),
                ('text_yes_future_prof', models.CharField(max_length=500, null=True)),
                ('text_addict_future_prof', models.CharField(max_length=500, null=True)),
                ('text_help_prof_choice', models.CharField(max_length=500, null=True)),
                ('text_after_school', models.CharField(max_length=500, null=True)),
                ('text_one_have_chosen_inst', models.CharField(max_length=500, null=True)),
                ('text_many_have_chosen_inst', models.CharField(max_length=500, null=True)),
                ('text_why_this_inst', models.CharField(max_length=500, null=True)),
                ('text_one_have_chosen_training', models.CharField(max_length=500, null=True)),
                ('text_many_have_chosen_training', models.CharField(max_length=500, null=True)),
                ('text_coach_prepare_to_enter', models.CharField(max_length=500, null=True)),
                ('text_course_prepare_to_enter', models.CharField(max_length=500, null=True)),
                ('text_other_prepare_to_enter', models.CharField(max_length=500, null=True)),
                ('text_no_if_you_want_ugtu', models.CharField(max_length=500, null=True)),
                ('text_yes_if_you_want_ugtu', models.CharField(max_length=500, null=True)),
                ('text_if_you_want_ugtu_training', models.CharField(max_length=500, null=True)),
                ('text_students_life', models.CharField(max_length=500, null=True)),
                ('help_prof_choice', models.ManyToManyField(to='tests.HelpProfChoice')),
                ('prepare_to_enter', models.ManyToManyField(to='tests.PrepareToEnter')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Schools')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Сфера')),
            ],
            options={
                'verbose_name_plural': 'Сферы студенческой жизни',
                'verbose_name': 'Сфера студенческой жизни',
            },
        ),
        migrations.CreateModel(
            name='WhyThisInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Критерий')),
            ],
            options={
                'verbose_name_plural': 'Критерии выбора ВУЗа',
                'verbose_name': 'Критерии выбора ВУЗа',
            },
        ),
        migrations.AlterField(
            model_name='contacts',
            name='middle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='middle_contacts', to='tests.Middle'),
        ),
        migrations.AlterField(
            model_name='respondentinterests',
            name='middle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='tests.Middle'),
        ),
        migrations.AddField(
            model_name='senior',
            name='students_life',
            field=models.ManyToManyField(to='tests.StudentsLife'),
        ),
        migrations.AddField(
            model_name='senior',
            name='why_this_inst',
            field=models.ManyToManyField(to='tests.WhyThisInst'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='senior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senior_contacts', to='tests.Senior'),
        ),
        migrations.AddField(
            model_name='respondentinterests',
            name='senior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senior_interests', to='tests.Senior'),
        ),
    ]
