# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2016-04-22 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20160422_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior',
            name='prepare_to_enter',
            field=models.ManyToManyField(to='tests.PrepareToEnter'),
        ),
        migrations.AlterField(
            model_name='senior',
            name='why_this_inst',
            field=models.ManyToManyField(to='tests.WhyThisInst'),
        ),
    ]
